version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: advert-db
    ports:
      - '5432:5432'

  backend:
    build: ./advertapp-api
    container_name: backend-container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/advert-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      APP_CORS_ALLOWED_ORIGINS: http://frontend:3000 # is ignored for now
    depends_on:
      - db
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./advertapp-ui
      args:
        BACKEND_BASE_URI: http://${HOST_IP}:8080
    container_name: frontend-container
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '3000:3000'
