spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advert-db
    username: postgres
    password: password
  sql:
    init:
      mode: always
  security:
    user:
      password: password

app:
  cors:
    allowed-origins: http://localhost:3000