spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  sql:
    init:
      mode: always
  security:
    user:
      password: password

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}

image-storage-dir: "${user.home}/static"